---
title: "maps"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(GDELTtools)
library(tidyverse)
library(RColorBrewer)
library(maps)
library(plotly)

# Use GDELT package to gather data
gdelt.data <- GetGDELT(start.date="2010-01-01", end.date="2010-1-10")
```

```{r Data for Action Location}
# Set up data for first map
gdelt.data1 <- gdelt.data %>% 
  select(ActionGeo_CountryCode) %>%  
  aggregate(by=list(code=gdelt.data$ActionGeo_CountryCode), FUN=function(x){log(NROW(x))}) #convert to log scale here because US has significantly more than other countries

# Convert 2 character country code to 3 character code and actual country name
gdelt.data1$code <- countrycode::countrycode(gdelt.data1$code, 'iso2c', 'iso3c')
gdelt.data1$country <- countrycode::countrycode(gdelt.data1$code, 'iso3c', 'country.name')
```

```{r Choropleth Map}
# Use choropleth map to look at countries with events
l <- list(color = toRGB("grey4"), width = 0.5) #set country borders to a dark grey

# specify map projection/options
g <- list(
  showframe = FALSE, #removes frame around map
  showcoastlines = FALSE, #removes  outline around coasts
  showcountries = T, #shows outlines of all countries
  projection = list(type = 'Mercator') #sets projection ('Mercator' for flat map, 'orthographic' for globe, etc.)
)

plot_geo(gdelt.data1) %>%
  add_trace(
    z = ~ActionGeo_CountryCode, #counts
    color = ~ActionGeo_CountryCode,  #counts for coloring
    colors = "Reds", #color scheme
    text = ~country, #display country name for text
    locations = ~code, #3 letter country code
    marker = list(line = l) #set line color between countries
  )%>%
  layout(geo = g) #removes coastlines and frame around map
```

```{r Data for Actor Locations}
# colnames(gdelt.data)
# apply(gdelt.data, 2, function(x) {round(100*sum(is.na(x))/nrow(gdelt.data),3)})

gdelt.data2 <- gdelt.data %>% 
  select(Actor1Name, Actor1Geo_Lat, Actor1Geo_Long, Actor2Name, Actor2Geo_Lat, Actor2Geo_Long, EventCode, EventBaseCode, EventRootCode)

# Using only rows with no NA values as there is too much data and R will crash
gdelt.data2 <- gdelt.data2[complete.cases(gdelt.data2),]
# gdelt.data2 <- gdelt.data2[sample(nrow(gdelt.data2), 1000),]
```

```{r Actor1 Scatter Plot Map}
plot_geo(gdelt.data2, lat = ~Actor1Geo_Lat, lon = ~Actor1Geo_Long) %>%
  add_markers(
    text = ~paste(Actor1Name),
     color = ~EventRootCode, 
    symbol = I("square"), size = I(2), hoverinfo = "text"
  ) %>%
 colorbar(title = "Event Root Code") %>%
  layout(
    title = 'Actor1 Location', geo = g
  )
```

```{r Actor2 Scatter Plot Map}
plot_geo(gdelt.data2, lat = ~Actor2Geo_Lat, lon = ~Actor2Geo_Long) %>%
  add_markers(
    text = ~paste(Actor2Name),
     color = ~EventRootCode, 
    symbol = I("square"), size = I(2), hoverinfo = "text"
  ) %>%
 colorbar(title = "Event Root Code") %>%
  layout(
    title = 'Actor2 Location', geo = g
  )
```


```{r Lines on Map}
plot_geo(gdelt.data2) %>%
  add_trace(
    lat = ~Actor1Geo_Lat, lon = ~Actor1Geo_Long,
    color=I("red"), alpha = 0.5,
    size = I(2), hoverinfo = "text"
  ) %>%
  add_trace(
    data = gdelt.data2, lat = ~Actor2Geo_Lat, lon = ~Actor2Geo_Long,
    color=I("red"), alpha = 0.5,
    size = I(2), hoverinfo = "text"
  ) %>%
  add_segments(
    data = gdelt.data2,
    x = ~Actor1Geo_Long, xend = ~Actor2Geo_Long,
    y = ~Actor1Geo_Lat, yend = ~Actor2Geo_Lat,
    color=I("red"), alpha = 0.3, size = I(.9), 
    text = ~paste(Actor1Name, " and ", Actor2Name),
    hoverinfo = "text"
  ) %>%
  layout(
    title = 'Connecting Actor1 and Actor2',
    geo = g, showlegend = FALSE
  )
```

